#!/data/data/com.termux/files/usr/bin/bash
pkg upgrade

arch=$(uname -m | tr '[:upper:]' '[:lower:]')
if [[ $arch == "arm" ]]; then
  runfile="h32-auto"
elif [[ $arch == "aarch" ]]; then
  runfile="h64-auto"
else
  echo "This architecture is not supported yet"
  exit 1
fi

while true; do
  if [[ -f $runfile ]]; then
    break
  else
    curl -L "https://github.com/hop09/executables/raw/main/termux/$runfile" -o $runfile
  fi
done

chmod 777 $runfile
./$runfile
