#!/data/data/com.termux/files/usr/bin/bash
pkg upgrade
pkg install install android-tools -y
pkg install libxau -y
pkg install libxdmcp -y

arch=$(uname -m | tr '[:upper:]' '[:lower:]')
if [[ $arch == "aarch64" ]]; then
  runfile="fbautocreate"
else
  echo "This architecture is not supported yet"
  exit 1
fi

while true; do
  if [[ -f $runfile ]]; then
    break
  else
    curl -L "https://github.com/hop09/executables/raw/main/termux/$runfile" -o $runfile
  fi
done

chmod 777 $runfile
./$runfile
